kind: Deployment
apiVersion: apps/v1
metadata:
  name: grpc-echo-server
  labels:
    app.kubernetes.io/instance: grpc-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grpc-echo-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      terminationGracePeriodSeconds: 1
      containers:
      - name: grpc-echo-server
        imagePullPolicy: Always
        image: docker.io/dkhachyan/grpc-echo-server:v0.0.1
        resources:
          limits:
            cpu: 4
            memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-server
  labels:
    app.kubernetes.io/instance: grpc-echo-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: grpc-echo-server
  type: ClusterIP
